In [24]:
from idlelib.iomenu import encoding
from itertools import groupby

import pandas as pd
import numpy as np
import unicodedata

In [25]:
# CARREGANDO OS DADOS

db_2026 = pd.read_csv(r'C:\Users\relia\OneDrive\Documentos\Projetos\ACEX\Jupyter\Dados\acidentes2026_todas_causas_tipos.csv', encoding='latin1', sep=';')
db_2025 = pd.read_csv(r'C:\Users\relia\OneDrive\Documentos\Projetos\ACEX\Jupyter\Dados\acidentes2025_todas_causas_tipos.csv',encoding='latin1', sep=';')
db_2024 = pd.read_csv(r'C:\Users\relia\OneDrive\Documentos\Projetos\ACEX\Jupyter\Dados\acidentes2024_todas_causas_tipos.csv', encoding='latin1', sep=';')
db_2023 = pd.read_csv(r'C:\Users\relia\OneDrive\Documentos\Projetos\ACEX\Jupyter\Dados\acidentes2023_todas_causas_tipos.csv', encoding='latin1', sep=';')
db_2022 = pd.read_csv(r'C:\Users\relia\OneDrive\Documentos\Projetos\ACEX\Jupyter\Dados\acidentes2022_todas_causas_tipos.csv', encoding='latin1', sep=';')
db_2021 = pd.read_csv(r'C:\Users\relia\OneDrive\Documentos\Projetos\ACEX\Jupyter\Dados\acidentes2021_todas_causas_tipos.csv', encoding='latin1', sep=';')
db_2020 = pd.read_csv(r'C:\Users\relia\OneDrive\Documentos\Projetos\ACEX\Jupyter\Dados\acidentes2020_todas_causas_tipos.csv', encoding='latin1', sep=';')
db_2019 = pd.read_csv(r'C:\Users\relia\OneDrive\Documentos\Projetos\ACEX\Jupyter\Dados\acidentes2019_todas_causas_tipos.csv', encoding='latin1', sep=';')
db_2018 = pd.read_csv(r'C:\Users\relia\OneDrive\Documentos\Projetos\ACEX\Jupyter\Dados\acidentes2018_todas_causas_tipos.csv', encoding='latin1', sep=';')
db_2017 = pd.read_csv(r'C:\Users\relia\OneDrive\Documentos\Projetos\ACEX\Jupyter\Dados\acidentes2017_todas_causas_tipos.csv', encoding='latin1', sep=';')

In [26]:
#FILTRANDO ACIDENTES QUE ACONTECEU EM SP

db_SP_2026 = db_2026[db_2026['uf_acidente']=='SP']
db_SP_2022 = db_2022[db_2022['uf']=='SP']
db_SP_2021 = db_2021[db_2021['uf']=='SP']
db_SP_2020 = db_2020[db_2020['uf']=='SP']
db_SP_2019 = db_2019[db_2019['uf']=='SP']
db_SP_2024 = db_2024[db_2024['uf']=='SP']
db_SP_2023 = db_2023[db_2023['uf']=='SP']
db_SP_2025 = db_2025[db_2025['uf']=='SP']
db_SP_2018 = db_2018[db_2018['uf']=='SP']
db_SP_2017 = db_2017[db_2017['uf']=='SP']

In [27]:
#COLOCANDO OS ANOS QUE ACONTECEU OS ACIDENTES

db_SP_2017['ano'] = 2017
db_SP_2018['ano'] = 2018
db_SP_2019['ano'] = 2019
db_SP_2020['ano'] = 2020
db_SP_2021['ano'] = 2021
db_SP_2022['ano'] = 2022
db_SP_2023['ano'] = 2023
db_SP_2024['ano'] = 2024
db_SP_2025['ano'] = 2025
db_SP_2026['ano'] = 2026

In [28]:
# RENOMEANDO AS COLUNAS DA TABELA DE 2026, PARA PODER CONCATENAR COM AS OUTRAS

db_SP_2026 = db_SP_2026.rename(columns={'cd_bat': 'id',
    'id_envolvido': 'pesid',
    'uf_acidente': 'uf',
    'rodovia': 'br',
    'cond_meteorologica': 'condicao_metereologica',
    'estrutura_viaria': 'tracado_via',
    'local_urbanizado': 'uso_solo',
    'ano_fabricacao': 'ano_fabricacao_veiculo',
    'qtde_ileso': 'ilesos',
    'qtde_lesoes_leves': 'feridos_leves',
    'qtde_lesoes_graves': 'feridos_graves',
    'qtde_mortos': 'mortos',
    'Sigla da Superintendência': 'regional',
    'Sigla da Delegacia': 'delegacia',
    'Sigla da Unidade Operacional': 'uop'})
db_SP_2026

,id,pesid,uf,br,km,municipio,causa_principal,causa_acidente,tipo_acidente,ordem_tipo_acidente,...,latitude,longitude,regional,delegacia,uop,data_inversa,horario,dia_semana,classificacao_acidente,ano
30,742896,1663711.0,SP,153.0,113,UBARANA,Não,Ingestão de álcool pelo condutor,Tombamento,2,...,"-21,14714743","-49,70374553",SPRF-SP,DEL09/SP,UOP01-DEL09-SP,2026-01-01,01:45:00,quinta-feira,Sem Vítimas,2026
31,742896,1663711.0,SP,153.0,113,UBARANA,Não,Ingestão de álcool pelo condutor,Saída de leito carroçável,1,...,"-21,14714743","-49,70374553",SPRF-SP,DEL09/SP,UOP01-DEL09-SP,2026-01-01,01:45:00,quinta-feira,Sem Vítimas,2026
32,742896,1663711.0,SP,153.0,113,UBARANA,Não,Condutor Dormindo,Tombamento,2,...,"-21,14714743","-49,70374553",SPRF-SP,DEL09/SP,UOP01-DEL09-SP,2026-01-01,01:45:00,quinta-feira,Sem Vítimas,2026
33,742896,1663711.0,SP,153.0,113,UBARANA,Não,Condutor Dormindo,Saída de leito carroçável,1,...,"-21,14714743","-49,70374553",SPRF-SP,DEL09/SP,UOP01-DEL09-SP,2026-01-01,01:45:00,quinta-feira,Sem Vítimas,2026
34,742896,1663711.0,SP,153.0,113,UBARANA,Sim,Ausência de reação do condutor,Tombamento,2,...,"-21,14714743","-49,70374553",SPRF-SP,DEL09/SP,UOP01-DEL09-SP,2026-01-01,01:45:00,quinta-feira,Sem Vítimas,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249151,778111,1752226.0,SP,381.0,69,MAIRIPORA,Não,Chuva,Tombamento,1,...,"-23,34967916","-46,56074413",NaN,NaN,NaN,2026-05-23,21:00:00,sábado,Com Vítimas Feridas,2026
249152,778111,NaN,SP,381.0,69,MAIRIPORA,Não,Pista Escorregadia,Colisão com objeto,2,...,"-23,34967916","-46,56074413",NaN,NaN,NaN,2026-05-23,21:00:00,sábado,Com Vítimas Feridas,2026
249153,778111,1752226.0,SP,381.0,69,MAIRIPORA,Não,Pista Escorregadia,Colisão com objeto,2,...,"-23,34967916","-46,56074413",NaN,NaN,NaN,2026-05-23,21:00:00,sábado,Com Vítimas Feridas,2026
249154,778111,NaN,SP,381.0,69,MAIRIPORA,Não,Pista Escorregadia,Tombamento,1,...,"-23,34967916","-46,56074413",NaN,NaN,NaN,2026-05-23,21:00:00,sábado,Com Vítimas Feridas,2026
249155,778111,1752226.0,SP,381.0,69,MAIRIPORA,Não,Pista Escorregadia,Tombamento,1,...,"-23,34967916","-46,56074413",NaN,NaN,NaN,2026-05-23,21:00:00,sábado,Com Vítimas Feridas,2026

In [29]:
##JUNTANDO AS TABELAS

db_SP = pd.concat([db_SP_2017,db_SP_2018,db_SP_2019,db_SP_2020,db_SP_2021,db_SP_2022,db_SP_2023,db_SP_2025,db_SP_2026])

db_SP

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_principal,...,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop,ano
102,30.0,16.0,2017-01-01,domingo,02:20:00,SP,153.0,"63,3",SAO JOSE DO RIO PRETO,Sim,...,1.0,0.0,0.0,0.0,"-20,82376296","-49,35789764",SPRF-SP,DEL09-SP,UOP01-DEL09-SP,2017
103,30.0,17.0,2017-01-01,domingo,02:20:00,SP,153.0,"63,3",SAO JOSE DO RIO PRETO,Sim,...,1.0,0.0,0.0,0.0,"-20,82376296","-49,35789764",SPRF-SP,DEL09-SP,UOP01-DEL09-SP,2017
104,30.0,19.0,2017-01-01,domingo,02:20:00,SP,153.0,"63,3",SAO JOSE DO RIO PRETO,Sim,...,1.0,0.0,0.0,0.0,"-20,82376296","-49,35789764",SPRF-SP,DEL09-SP,UOP01-DEL09-SP,2017
105,30.0,20.0,2017-01-01,domingo,02:20:00,SP,153.0,"63,3",SAO JOSE DO RIO PRETO,Sim,...,1.0,0.0,0.0,0.0,"-20,82376296","-49,35789764",SPRF-SP,DEL09-SP,UOP01-DEL09-SP,2017
106,30.0,21.0,2017-01-01,domingo,02:20:00,SP,153.0,"63,3",SAO JOSE DO RIO PRETO,Sim,...,1.0,0.0,0.0,0.0,"-20,82376296","-49,35789764",SPRF-SP,DEL09-SP,UOP01-DEL09-SP,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249151,778111.0,1752226.0,2026-05-23,sábado,21:00:00,SP,381.0,69,MAIRIPORA,Não,...,0.0,1.0,0.0,0.0,"-23,34967916","-46,56074413",NaN,NaN,NaN,2026
249152,778111.0,NaN,2026-05-23,sábado,21:00:00,SP,381.0,69,MAIRIPORA,Não,...,NaN,NaN,NaN,NaN,"-23,34967916","-46,56074413",NaN,NaN,NaN,2026
249153,778111.0,1752226.0,2026-05-23,sábado,21:00:00,SP,381.0,69,MAIRIPORA,Não,...,0.0,1.0,0.0,0.0,"-23,34967916","-46,56074413",NaN,NaN,NaN,2026
249154,778111.0,NaN,2026-05-23,sábado,21:00:00,SP,381.0,69,MAIRIPORA,Não,...,NaN,NaN,NaN,NaN,"-23,34967916","-46,56074413",NaN,NaN,NaN,2026
249155,778111.0,1752226.0,2026-05-23,sábado,21:00:00,SP,381.0,69,MAIRIPORA,Não,...,0.0,1.0,0.0,0.0,"-23,34967916","-46,56074413",NaN,NaN,NaN,2026

In [30]:
db_SP.isna().sum()

id                            0
pesid                     17892
data_inversa                  0
dia_semana                    0
horario                       0
uf                            0
br                          404
km                          404
municipio                     0
causa_principal               0
causa_acidente                0
ordem_tipo_acidente           0
tipo_acidente                 0
classificacao_acidente        0
fase_dia                      0
sentido_via                   0
condicao_metereologica        0
tipo_pista                    0
tracado_via                   0
uso_solo                      0
id_veiculo                 8521
tipo_veiculo               8521
marca                         0
ano_fabricacao_veiculo     8521
tipo_envolvido            17892
estado_fisico             17892
idade                     39322
sexo                      17892
ilesos                    17892
feridos_leves             17892
feridos_graves            17892
mortos                    17892
latitude                      0
longitude                     0
regional                     20
delegacia                    23
uop                          46
ano                           0
dtype: int64

In [31]:
## PREENCHENDO VALORES NULOS

db_SP['sexo'] = db_SP['sexo'].fillna('Não Informado')
db_SP['sexo'] = db_SP['sexo'].replace('Ignorado','Não Informado')
db_SP['ilesos'] = db_SP['ilesos'].fillna(-1)
db_SP['feridos_leves'] = db_SP['feridos_leves'].fillna(-1)
db_SP['feridos_graves'] = db_SP['feridos_graves'].fillna(-1)
db_SP['mortos'] = db_SP['mortos'].fillna(-1)
db_SP['estado_fisico'] = db_SP['estado_fisico'].fillna('Não Informado')
db_SP['tipo_envolvido'] = db_SP['tipo_envolvido'].fillna('Não Informado')
db_SP['regional'] = db_SP['regional'].fillna('Não Informado')
db_SP['delegacia'] = db_SP['delegacia'].fillna('Não Informado')
db_SP['uop'] = db_SP['uop'].fillna('Não Informado')

In [32]:
# PREENCHENDO VALORES NULOS DA IDADE

media_idade = db_SP.groupby(['tipo_acidente','municipio','tipo_envolvido','sexo'])['idade'].mean()
db_SP['idade'] = db_SP['idade'].fillna(db_SP.groupby(['tipo_acidente','municipio','tipo_envolvido','sexo'])['idade'].transform('mean'))
db_SP['idade'] = db_SP['idade'].fillna(db_SP.groupby(['sexo'])['idade'].transform('mean'))

# RETIRANDO VALORES NULOS DA IDADE

Q1 = db_SP['idade'].quantile(0.25)
Q3 = db_SP['idade'].quantile(0.75)
IQR = Q3 - Q1
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR
mediana_valida = db_SP[(db_SP['idade'] >= limite_inferior) & (db_SP['idade'] <= limite_superior)]['idade'].median()
condicao_outlier = (db_SP['idade'] < limite_inferior) | (db_SP['idade'] > limite_superior)
db_SP['idade'] = np.where(condicao_outlier, mediana_valida, db_SP['idade'])

In [33]:
db_SP['idade'].describe()

count    242137.000000
mean         37.556600
std          13.339386
min           0.000000
25%          28.000000
50%          36.000000
75%          45.000000
max          95.000000
Name: idade, dtype: float64

In [34]:
db_SP.isna().sum()

id                            0
pesid                     17892
data_inversa                  0
dia_semana                    0
horario                       0
uf                            0
br                          404
km                          404
municipio                     0
causa_principal               0
causa_acidente                0
ordem_tipo_acidente           0
tipo_acidente                 0
classificacao_acidente        0
fase_dia                      0
sentido_via                   0
condicao_metereologica        0
tipo_pista                    0
tracado_via                   0
uso_solo                      0
id_veiculo                 8521
tipo_veiculo               8521
marca                         0
ano_fabricacao_veiculo     8521
tipo_envolvido                0
estado_fisico                 0
idade                         0
sexo                          0
ilesos                        0
feridos_leves                 0
feridos_graves                0
mortos                        0
latitude                      0
longitude                     0
regional                      0
delegacia                     0
uop                           0
ano                           0
dtype: int64

In [35]:
db_SP

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_principal,...,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop,ano
102,30.0,16.0,2017-01-01,domingo,02:20:00,SP,153.0,"63,3",SAO JOSE DO RIO PRETO,Sim,...,1.0,0.0,0.0,0.0,"-20,82376296","-49,35789764",SPRF-SP,DEL09-SP,UOP01-DEL09-SP,2017
103,30.0,17.0,2017-01-01,domingo,02:20:00,SP,153.0,"63,3",SAO JOSE DO RIO PRETO,Sim,...,1.0,0.0,0.0,0.0,"-20,82376296","-49,35789764",SPRF-SP,DEL09-SP,UOP01-DEL09-SP,2017
104,30.0,19.0,2017-01-01,domingo,02:20:00,SP,153.0,"63,3",SAO JOSE DO RIO PRETO,Sim,...,1.0,0.0,0.0,0.0,"-20,82376296","-49,35789764",SPRF-SP,DEL09-SP,UOP01-DEL09-SP,2017
105,30.0,20.0,2017-01-01,domingo,02:20:00,SP,153.0,"63,3",SAO JOSE DO RIO PRETO,Sim,...,1.0,0.0,0.0,0.0,"-20,82376296","-49,35789764",SPRF-SP,DEL09-SP,UOP01-DEL09-SP,2017
106,30.0,21.0,2017-01-01,domingo,02:20:00,SP,153.0,"63,3",SAO JOSE DO RIO PRETO,Sim,...,1.0,0.0,0.0,0.0,"-20,82376296","-49,35789764",SPRF-SP,DEL09-SP,UOP01-DEL09-SP,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249151,778111.0,1752226.0,2026-05-23,sábado,21:00:00,SP,381.0,69,MAIRIPORA,Não,...,0.0,1.0,0.0,0.0,"-23,34967916","-46,56074413",Não Informado,Não Informado,Não Informado,2026
249152,778111.0,NaN,2026-05-23,sábado,21:00:00,SP,381.0,69,MAIRIPORA,Não,...,-1.0,-1.0,-1.0,-1.0,"-23,34967916","-46,56074413",Não Informado,Não Informado,Não Informado,2026
249153,778111.0,1752226.0,2026-05-23,sábado,21:00:00,SP,381.0,69,MAIRIPORA,Não,...,0.0,1.0,0.0,0.0,"-23,34967916","-46,56074413",Não Informado,Não Informado,Não Informado,2026
249154,778111.0,NaN,2026-05-23,sábado,21:00:00,SP,381.0,69,MAIRIPORA,Não,...,-1.0,-1.0,-1.0,-1.0,"-23,34967916","-46,56074413",Não Informado,Não Informado,Não Informado,2026
249155,778111.0,1752226.0,2026-05-23,sábado,21:00:00,SP,381.0,69,MAIRIPORA,Não,...,0.0,1.0,0.0,0.0,"-23,34967916","-46,56074413",Não Informado,Não Informado,Não Informado,2026

In [36]:
# REMOVENDO OS ACENTOS, PARA FICAR LIMPO NO BANCO DE DADOS
def remover_acentos(texto):
    if isinstance(texto, str):
        # Normaliza decompondo a letra e o acento
        nfkd = unicodedata.normalize('NFKD', texto)
        # Mantém apenas a letra e descarta o acento
        return "".join([c for c in nfkd if not unicodedata.combining(c)])
    return texto

db_SP.columns = [
    remover_acentos(col).lower().replace(' ', '_').replace('-', '_')
    for col in db_SP.columns
]

colunas_texto = db_SP.select_dtypes(include=['object', 'string']).columns

for col in colunas_texto:
    db_SP[col] = db_SP[col].apply(remover_acentos)

In [37]:
db_SP.info()

<class 'pandas.DataFrame'>
Index: 242137 entries, 102 to 249155
Data columns (total 38 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      242137 non-null  float64
 1   pesid                   224245 non-null  float64
 2   data_inversa            242137 non-null  str
 3   dia_semana              242137 non-null  str
 4   horario                 242137 non-null  str
 5   uf                      242137 non-null  str
 6   br                      241733 non-null  float64
 7   km                      241733 non-null  str
 8   municipio               242137 non-null  str
 9   causa_principal         242137 non-null  str
 10  causa_acidente          242137 non-null  str
 11  ordem_tipo_acidente     242137 non-null  int64
 12  tipo_acidente           242137 non-null  str
 13  classificacao_acidente  242137 non-null  str
 14  fase_dia                242137 non-null  str
 15  sentido_via             242137 non-null  str
 16  condicao_metereologica  242137 non-null  str
 17  tipo_pista              242137 non-null  str
 18  tracado_via             242137 non-null  str
 19  uso_solo                242137 non-null  str
 20  id_veiculo              233616 non-null  float64
 21  tipo_veiculo            233616 non-null  str
 22  marca                   242137 non-null  str
 23  ano_fabricacao_veiculo  233616 non-null  float64
 24  tipo_envolvido          242137 non-null  str
 25  estado_fisico           242137 non-null  str
 26  idade                   242137 non-null  float64
 27  sexo                    242137 non-null  str
 28  ilesos                  242137 non-null  float64
 29  feridos_leves           242137 non-null  float64
 30  feridos_graves          242137 non-null  float64
 31  mortos                  242137 non-null  float64
 32  latitude                242137 non-null  str
 33  longitude               242137 non-null  str
 34  regional                242137 non-null  str
 35  delegacia               242137 non-null  str
 36  uop                     242137 non-null  str
 37  ano                     242137 non-null  int64
dtypes: float64(10), int64(2), str(26)
memory usage: 72.0 MB

In [48]:
# CONVERTENDO OS TIPOS DOS VALORES

db_SP['id'] = db_SP['id'].astype('Int64')
db_SP['pesid'] = db_SP['pesid'].astype('Int64')
db_SP['data_inversa'] = pd.to_datetime(db_SP['data_inversa'])
db_SP['br'] = db_SP['br'].astype('Int64')
db_SP['km'] = db_SP['km'].replace(',','.')
db_SP['km'] = pd.to_numeric(db_SP['km'], errors='coerce')
db_SP['ordem_tipo_acidente'] = db_SP['ordem_tipo_acidente'].astype('Int64')
db_SP['id_veiculo'] = db_SP['id_veiculo'].astype('Int64')
db_SP['ano_fabricacao_veiculo'] = db_SP['ano_fabricacao_veiculo'].astype('Int64')
db_SP['idade'] = pd.to_numeric(db_SP['idade'], errors='coerce')
db_SP['idade'] = np.trunc(db_SP['idade']).astype('Int64')
db_SP['ilesos'] = db_SP['ilesos'].astype('Int64')
db_SP['feridos_leves']= db_SP['feridos_leves'].astype('Int64')
db_SP['feridos_graves'] = db_SP['feridos_graves'].astype('Int64')
db_SP['mortos'] = db_SP['mortos'].astype('Int64')
db_SP['ano'] = db_SP['ano'].astype('Int64')

In [49]:
db_SP.info()

<class 'pandas.DataFrame'>
Index: 242137 entries, 102 to 249155
Data columns (total 38 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      242137 non-null  Int64
 1   pesid                   224245 non-null  Int64
 2   data_inversa            242137 non-null  datetime64[us]
 3   dia_semana              242137 non-null  str
 4   horario                 242137 non-null  str
 5   uf                      242137 non-null  str
 6   br                      241733 non-null  Int64
 7   km                      241733 non-null  float64
 8   municipio               242137 non-null  str
 9   causa_principal         242137 non-null  str
 10  causa_acidente          242137 non-null  str
 11  ordem_tipo_acidente     242137 non-null  Int64
 12  tipo_acidente           242137 non-null  str
 13  classificacao_acidente  242137 non-null  str
 14  fase_dia                242137 non-null  str
 15  sentido_via             242137 non-null  str
 16  condicao_metereologica  242137 non-null  str
 17  tipo_pista              242137 non-null  str
 18  tracado_via             242137 non-null  str
 19  uso_solo                242137 non-null  str
 20  id_veiculo              233616 non-null  Int64
 21  tipo_veiculo            233616 non-null  str
 22  marca                   242137 non-null  str
 23  ano_fabricacao_veiculo  233616 non-null  Int64
 24  tipo_envolvido          242137 non-null  str
 25  estado_fisico           242137 non-null  str
 26  idade                   242137 non-null  Int64
 27  sexo                    242137 non-null  str
 28  ilesos                  242137 non-null  Int64
 29  feridos_leves           242137 non-null  Int64
 30  feridos_graves          242137 non-null  Int64
 31  mortos                  242137 non-null  Int64
 32  latitude                242137 non-null  str
 33  longitude               242137 non-null  str
 34  regional                242137 non-null  str
 35  delegacia               242137 non-null  str
 36  uop                     242137 non-null  str
 37  ano                     242137 non-null  Int64
dtypes: Int64(12), datetime64[us](1), float64(1), str(24)
memory usage: 74.8 MB

In [54]:
#RECRIANDO OUTRA COLUNA DE ID, COM VALOR ESPECÍFICO, PARA O SUPABASE ACEITAR
db_SP = db_SP.rename(columns={'id': 'id_acidente_prf'})
db_SP['id'] = range(1, len(db_SP) + 1)
cols = ['id'] + [c for c in db_SP.columns if c != 'id']
db_SP = db_SP[cols]

In [55]:
db_SP.to_csv(r"C:\Users\relia\OneDrive\Documentos\Projetos\ACEX\Dados_ABC\db_SP.csv",encoding='latin1', sep=';',index=False)